version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: fleetsignal-postgres
    environment:
      POSTGRES_USER: motorq
      POSTGRES_PASSWORD: motorq_password
      POSTGRES_DB: fleetsignal
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/migrations/postgres:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 400M

  clickhouse:
    image: clickhouse/clickhouse-server:24.1-alpine
    container_name: fleetsignal-clickhouse
    environment:
      CLICKHOUSE_DB: fleetsignal
      CLICKHOUSE_USER: motorq
      CLICKHOUSE_PASSWORD: motorq_password
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./infrastructure/migrations/clickhouse:/docker-entrypoint-initdb.d
      - clickhouse_data:/var/lib/clickhouse
    deploy:
      resources:
        limits:
          memory: 384M

  redis:
    image: redis:7-alpine
    container_name: fleetsignal-redis
    command: redis-server --maxmemory 48mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 64M

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: fleetsignal-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    deploy:
      resources:
        limits:
          memory: 400M

  kafka-init:
    image: confluentinc/cp-kafka:7.5.0
    container_name: fleetsignal-kafka-init
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:29092 --list
      
      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic vehicle.telemetry --partitions 3 --replication-factor 1
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic incident.alerts --partitions 1 --replication-factor 1
      
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:29092 --list
      "

volumes:
  pgdata:
  clickhouse_data:
  kafka_data:
