site_name: FleetSignal Internal Docs
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
nav:
  - Overview: index.md
  - Architecture: architecture.md
  - Privacy Engine: privacy.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
